Refactor vring abstraction
rust-vmm/vhost-user-backend pull request #30
Opened 2021-09-01 06:38 UTC by jiangliu

Add `trait VringT` and provide three implementation of it: VringState, VringMutex, VringRwLock,
so clients could choose different implementation.

2021-09-01 11:38 UTC, stefano-garzarella requested changes
The refactor looks great, just a couple of simple copy&paste typos :-)

2021-09-01 11:38 UTC, stefano-garzarella commented on src/vring.rs
> +/// Struct to hold an shared reference to the underlying `VringState` object.
s/an/a

2021-09-01 11:38 UTC, stefano-garzarella commented on src/vring.rs
> +    /// Get an immutable reference to the kick event fd.
s/immutable/mutable

2021-09-01 11:38 UTC, stefano-garzarella commented on src/vring.rs
> +    /// Read event from the kick EventFd.
Maybe add `` to EventFd as other comments?

2021-09-01 11:53 UTC, stefano-garzarella approved these changes

2021-09-01 12:21 UTC, slp commented
Thanks for working on this. I must be missing something, but I can't find a way to access the underlying `Queue` in `VringState` to iterate over it. What's the pattern to lock the `Vring` and iterate on the `Queue` to get the descriptor chains?

2021-09-02 08:44 UTC, jiangliu commented
> Thanks for working on this. I must be missing something, but I can't find a way to access the underlying `Queue` in `VringState` to iterate over it. What's the pattern to lock the `Vring` and iterate on the `Queue` to get the descriptor chains?

I realized this issue and have updated the patch yesterday. Now we have "VringState::get_queue()" and "VringState::get_queue_mut()" for that purpose.
https://github.com/rust-vmm/vhost-user-backend/pull/30/files#diff-04f224919b2745af8bfb2d2aea4be7d9100e861a8a16f2cd0263cb1021b44c4dR151

2021-09-02 15:52 UTC, jiangliu commented
> > > Thanks for working on this. I must be missing something, but I can't find a way to access the underlying `Queue` in `VringState` to iterate over it. What's the pattern to lock the `Vring` and iterate on the `Queue` to get the descriptor chains?
> > 
> > 
> > I realized this issue and have updated the patch yesterday. Now we have "VringState::get_queue()" and "VringState::get_queue_mut()" for that purpose.
> > https://github.com/rust-vmm/vhost-user-backend/pull/30/files#diff-04f224919b2745af8bfb2d2aea4be7d9100e861a8a16f2cd0263cb1021b44c4dR151
> 
> Great, thanks!
> 
> I've tested this crate with virtiofsd, and was able to implement both a multi-threaded method and a single-threaded method for processing the queue, so I think this model should work for most consumers of this crate.
> 
> One change that I think could be interesting, is publishing `VringStateGuard` and `VringStateMutGuard` in the root of the crate (since `vring` is private). That allows consumers to acquire a reference to `VringState` (and thus, the underlying lock, if using `VringMutex` or `VringRwLock`) once and pass it around to other methods. What do you think about this?

Done:)

2021-09-03 07:21 UTC, slp commented
Thanks again! :-)

2021-09-03 07:21 UTC, slp submitted a review, later dismissed

2021-09-06 07:56 UTC, slp commented
@jiangliu Could you please rebase this on top of f0af5f7 ?

2021-09-07 06:33 UTC, slp approved these changes
LGTM (again), thanks!

2021-09-07 07:35 UTC, stefano-garzarella approved these changes

2021-09-07 08:32 UTC, merged